# Generated by Django 2.0.5 on 2018-08-21 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180821_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfilemodel',
            old_name='title',
            new_name='name',
        ),
    ]
