# Generated by Django 2.0.5 on 2018-08-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180821_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='name',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
